version: '3.9'
services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: sweetybear
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - mysql
    ports:
      - 4000:4000
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/sweetybear
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_OPEN_IN_VIEW=true
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=false
      - SPRING_WEB_RESOURCES_ADD_MAPPINGS=true
      - SPRING_FREEMARKER_EXPOSE_REQUEST_ATTRIBUTES=true
      - SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE=10MB
      - SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE=10MB
      - SPRING_MAIL_HOST=your_mail_host
      - SPRING_MAIL_USERNAME=your_mail_username
      - SPRING_MAIL_PASSWORD=your_mail_password
      - SPRING_MAIL_PORT=your_mail_port
      - SPRING_MAIL_PROTOCOL=your_mail_protocol
      - MAIL_DEBUG=true
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_ID=your_google_client_id
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_SECRET=your_google_client_secret
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_SCOPE=email,profile
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GITHUB_CLIENT_ID=your_github_client_id
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GITHUB_CLIENT_SECRET=your_github_client_secret
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GITHUB_SCOPE=user
